name: CI Pipeline # Назва процесу, яку ти побачиш на GitHub

on: # Коли запускати дії
  push: # При відправленні змін (git push)
    branches: [main] # Тільки для гілки "main"
  pull_request: # При створенні pull request
    branches: [main]

jobs: # Завдання, які виконуватимуться
  test: # Назва завдання (може бути будь-якою)
    runs-on: ubuntu-latest # Виконувати на віртуальній машині з Ubuntu

    steps: # Кроки завдання
      - uses: actions/checkout@v3 # Завантажити твій код із репозиторію

      - name: Set up Python # Налаштувати Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Використовувати Python 3 (будь-яка остання версія)

      - name: Install dependencies # Встановити бібліотеки
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest # Запустити тести
        run: |
          pytest --html=report.html --self-contained-html

      - name: Check PEP8 compliance # Перевірити код на PEP8
        run: |
          flake8 . --max-line-length=100

      - name: Upload test report # Зберегти звіт про тести
        uses: actions/upload-artifact@v3
        if: always() # Завантажувати навіть якщо тести не пройшли
        with:
          name: pytest-report # Назва звіту
          path: report.html # Шлях до файлу звіту
