name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest --html=report.html --self-contained-html

      - name: Debug - Check if report exists # Новий крок для перевірки
        run: |
          ls -la  # Команда, яка покаже всі файли в директорії

      - name: Check PEP8 compliance
        run: |
          flake8 . --max-line-length=100

      - name: Upload test report
        uses: actions/upload-artifact@v4 # Змінили v3 на v4
        if: always()
        with:
          name: pytest-report
          path: report.html
